-- 1. Script SQL de borrado y creación de las tablas, vistas y sinónimos.

-- BORRADO DE TABLAS.

DROP TABLE USUARIO;
DROP TABLE JUGADOR;
DROP TABLE STAFF;
DROP TABLE EQUIPO;
DROP TABLE PATROCINADOR;
DROP TABLE COMPETICION;
DROP TABLE JORNADA;
DROP TABLE ENFRENTAMIENTO;
DROP TABLE JUEGO;
DROP TABLE PATROCINADOR_EQUIPO;
DROP TABLE EQUIPO_COMPETICION;

select * from USUARIO;
select * from JUGADOR;
select * from STAFF;
select * from EQUIPO;
select * from PATROCINADOR;
select * from COMPETICION;
select * from JORNADA;
select * from ENFRENTAMIENTO;
select * from JUEGO;
select * from PATROCINADOR_EQUIPO;
select * from EQUIPO_COMPETICION;

-- CREACIÓN DE TABLAS.

CREATE TABLE USUARIO (
	NOM_USUARIO VARCHAR2(30),
	CONTRASENA VARCHAR2(10) NOT NULL,
	TIPO VARCHAR2(1) NOT NULL,
	CONSTRAINT USU_NOM_PK PRIMARY KEY (NOM_USUARIO),
	CONSTRAINT USU_TIPO_CK CHECK (TIPO IN ('A','N'))
);

CREATE TABLE JUGADOR (
	ID_JUGADOR NUMBER(2) GENERATED ALWAYS AS IDENTITY 
							INCREMENT BY 1
							START WITH 1
							MINVALUE 1
							MAXVALUE 99
							NOCACHE,
	NOMBRE VARCHAR2(30) NOT NULL,
	NICKNAME VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR2(30) NOT NULL,
	ROL VARCHAR2(30) NOT NULL,
	FECHA_NAC DATE NOT NULL,
	SUELDO NUMBER(9,2) NOT NULL,
	ID_EQUIPO NUMBER(2) NOT NULL,
	CONSTRAINT JUG_ID_PK PRIMARY KEY (ID_JUGADOR),
	CONSTRAINT JUG_SUEL_CK CHECK (SUELDO>1134),
	CONSTRAINT JUG_ID_EQUI_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE STAFF (
	ID_STAFF NUMBER(2) GENERATED ALWAYS AS IDENTITY 
							INCREMENT BY 1
							START WITH 1
							MINVALUE 1
							MAXVALUE 99
							NOCACHE,
	PUESTO VARCHAR2(30) NOT NULL,
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHA_NAC DATE NOT NULL,
	SUELDO NUMBER(9,2) NOT NULL,
	ID_EQUIPO NUMBER(2) NOT NULL,
	CONSTRAINT STAFF_ID_PK PRIMARY KEY (ID_STAFF),
	CONSTRAINT STAFF_ID_EQUI_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE PATROCINADOR (
	ID_PATROCINADOR NUMBER(2) GENERATED ALWAYS AS IDENTITY 
								INCREMENT BY 1
								START WITH 1
								MINVALUE 1
								MAXVALUE 99
								NOCACHE,
	NOMBRE VARCHAR2(30) NOT NULL,
	CONSTRAINT PAT_ID_PK PRIMARY KEY (ID_PATROCINADOR)
);

CREATE TABLE EQUIPO (
	ID_EQUIPO NUMBER(2) GENERATED ALWAYS AS IDENTITY 
						INCREMENT BY 1
						START WITH 1
						MINVALUE 1
						MAXVALUE 99
						NOCACHE,
	NOM_EQUIPO VARCHAR2(30) NOT NULL,
	FECHA_FUNDACION DATE NOT NULL,
	CONSTRAINT EQUI_ID_PK PRIMARY KEY (ID_EQUIPO)
);

CREATE TABLE COMPETICION (
	ID_COMPETICION NUMBER(2) GENERATED ALWAYS AS IDENTITY 
								INCREMENT BY 1
								START WITH 1
								MINVALUE 1
								MAXVALUE 99
								NOCACHE,
	NOMBRE_COM VARCHAR2(30) NOT NULL,
	FECHA_INICIO DATE NOT NULL,
	FECHA_FIN DATE NOT NULL,
	ETAPA VARCHAR2(2) NOT NULL,
	NOMBRE_JUEGO VARCHAR2(30) NOT NULL,
	ID_EQUIPO_GANADOR NUMBER(2) NOT NULL,
	CONSTRAINT COMP_ID_PK PRIMARY KEY (ID_COMPETICION),
	CONSTRAINT COMP_FECHA_CK CHECK (FECHA_INICIO<FECHA_FIN),
	CONSTRAINT COMP_ETAPA_CK CHECK (ETAPA IN ('A','C')),
	CONSTRAINT COMP_NOM_JUE_FK FOREIGN KEY (NOMBRE_JUEGO) REFERENCES JUEGO(NOMBRE),
	CONSTRAINT COMP_ID_EQUI_FK FOREIGN KEY (ID_EQUIPO_GANADOR) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE JORNADA (
	ID_JORNADA NUMBER(2) GENERATED ALWAYS AS IDENTITY 
								INCREMENT BY 1
								START WITH 1
								MINVALUE 1
								MAXVALUE 99
								NOCACHE,
	FECHA_JORNADA DATE NOT NULL,
	ID_COMPETICION NUMBER(2) NOT NULL,
	CONSTRAINT JOR_ID_PK PRIMARY KEY (ID_JORNADA),
	CONSTRAINT JOR_ID_COMP_FK FOREIGN KEY (ID_COMPETICION) REFERENCES COMPETICION(ID_COMPETICION)
);

CREATE TABLE ENFRENTAMIENTO (
	ID_ENFRENTAMIENTO NUMBER(2) GENERATED ALWAYS AS IDENTITY 
								INCREMENT BY 1
								START WITH 1
								MINVALUE 1
								MAXVALUE 99
								NOCACHE,
	HORA_ENFRENTAMIENTO TIMESTAMP NOT NULL,
	RESULTADO1 NUMBER(2) NOT NULL,
	RESULTADO2 NUMBER(2) NOT NULL,
	ID_EQUIPO1 NUMBER(2) NOT NULL,
	ID_EQUIPO2 NUMBER(2) NOT NULL,
	ID_JORNADA NUMBER(2) NOT NULL,
	CONSTRAINT ENF_ID_PK PRIMARY KEY (ID_ENFRENTAMIENTO),
	CONSTRAINT ENF_ID_EQUI1_FK FOREIGN KEY (ID_EQUIPO1) REFERENCES EQUIPO(ID_EQUIPO),
	CONSTRAINT ENF_ID_EQUI2_FK FOREIGN KEY (ID_EQUIPO2) REFERENCES EQUIPO(ID_EQUIPO),
	CONSTRAINT ENF_ID_JOR_FK FOREIGN KEY (ID_JORNADA) REFERENCES JORNADA(ID_JORNADA)
);

CREATE TABLE JUEGO (
	ID_JUEGO NUMBER(2),
	NOMBRE VARCHAR2(30),
	EMPRESA VARCHAR2(30) NOT NULL,
	FECHA_LANZAMIENTO DATE NOT NULL,
	CONSTRAINT JUE_NOM_PK PRIMARY KEY (NOMBRE)
);

CREATE TABLE PATROCINADOR_EQUIPO (
	ID_PATROCINADOR NUMBER(2),
	ID_EQUIPO NUMBER(2),
	CONSTRAINT PAT_EQUI_ID_PK PRIMARY KEY (ID_PATROCINADOR,ID_EQUIPO),
	CONSTRAINT PAT_EQUI_ID_PAT_FK FOREIGN KEY (ID_PATROCINADOR) REFERENCES PATROCINADOR(ID_PATROCINADOR),
	CONSTRAINT PAT_EQUI_ID_EQUI_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);

CREATE TABLE EQUIPO_COMPETICION (
	ID_EQUIPO NUMBER(2),
	ID_COMPETICION NUMBER(2),
	PUNTOS NUMBER(2),
	CONSTRAINT EQUI_COMP_ID_PK PRIMARY KEY (ID_EQUIPO,ID_COMPETICION),
	CONSTRAINT EQUI_COMP_ID_EQUI_FK FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO),
	CONSTRAINT EQUI_COMP_ID_COMP_FK FOREIGN KEY (ID_COMPETICION) REFERENCES COMPETICION(ID_COMPETICION)
);