-- 1. Script SQL de borrado y creacion de las vistas y sinonimos.

-- Comprobacion de los datos de las tablas.
SELECT * FROM USUARIOS;
SELECT * FROM JUGADORES;
SELECT * FROM STAFFS;
SELECT * FROM EQUIPOS;
SELECT * FROM PATROCINADORES;
SELECT * FROM COMPETICIONES;
SELECT * FROM JORNADAS;
SELECT * FROM ENFRENTAMIENTOS;
SELECT * FROM JUEGOS;
SELECT * FROM PATROCINADORES_EQUIPOS;
SELECT * FROM EQUIPOS_COMPETICIONES;

-- BORRADO Y CREACION DE VISTAS.

DROP VIEW VISTA_JUGADORES_EQUIPOS;
DROP VIEW VISTA_ENFRENTAMIENTOS_JORNADA;
DROP VIEW VISTA_EQUIPOS_COMPETICION;

-- Select que devuelve todos los jugadores con sus equipos correspondientes.
CREATE OR REPLACE VIEW VISTA_JUGADORES_EQUIPOS AS (
	SELECT J.ID_JUGADOR, J.NOMBRE, J.NICKNAME, J.NACIONALIDAD, E.ID_EQUIPO,
            E.NOM_EQUIPO
	FROM JUGADORES J, EQUIPOS E
	WHERE E.ID_EQUIPO = J.ID_EQUIPO
);

-- Select que devuelve los enfrentamientos que hay por jornada en una competicion.
CREATE OR REPLACE VIEW VISTA_ENFRENTAMIENTOS_JORNADA AS (
	SELECT  E.ID_ENFRENTAMIENTO,
            TO_CHAR(E.HORA_ENFRENTAMIENTO,'DD-MM-YY HH24:MI')
                AS "HORA_ENFRENTAMIENTO",
            E.ID_EQUIPO1 AS "ID_EQUIPO_1",
            E.RESULTADO1 AS "RESULTADO_EQUIPO_1",
            E.ID_EQUIPO2 AS "ID_EQUIPO_2",
            E.RESULTADO2 AS "RESULTADO_EQUIPO_2",
            J.NUM_JORNADA AS "NÚMERO_JORNADA", J.FECHA_JORNADA,
            C.ID_COMPETICION,
            C.NOMBRE_COM AS "NOMBRE_COMPETICION"
	FROM ENFRENTAMIENTOS E, JORNADAS J, COMPETICIONES C
	WHERE E.ID_JORNADA = J.ID_JORNADA
    AND J.ID_COMPETICION = C.ID_COMPETICION
);

/*
Relacion de los equipos que conforman la competicion, con todos los datos que
se tengan de la misma: nombre del juego, fechas, relacion de equipos
incluyendo para cada equipo el nombre del mismo, los miembros del
staff y la cantidad de jugadores que hay en ese equipo.
*/
CREATE OR REPLACE VIEW VISTA_EQUIPOS_COMPETICION AS (
	SELECT JUEGOS.NOMBRE AS "NOMBRE_JUEGO", COMPETICIONES.FECHA_INICIO,
            COMPETICIONES.FECHA_FIN, EQUIPOS.NOM_EQUIPO AS "NOMBRE_EQUIPO",
            STAFFS.NOMBRE AS "NOMBRE_STAFF",
            COUNT(JUGADORES.ID_JUGADOR) AS "NUMERO_JUGADORES"
    FROM EQUIPOS
    JOIN STAFFS ON EQUIPOS.ID_EQUIPO = STAFFS.ID_EQUIPO
    JOIN EQUIPOS_COMPETICIONES ON EQUIPOS.ID_EQUIPO =
        EQUIPOS_COMPETICIONES.ID_EQUIPO
    JOIN COMPETICIONES
        ON EQUIPOS_COMPETICIONES.ID_COMPETICION = COMPETICIONES.ID_COMPETICION
    JOIN JUEGOS ON COMPETICIONES.ID_JUEGO = JUEGOS.ID_JUEGO
    LEFT JOIN JUGADORES ON EQUIPOS.ID_EQUIPO = JUGADORES.ID_EQUIPO
    GROUP BY JUEGOS.NOMBRE, COMPETICIONES.FECHA_INICIO, COMPETICIONES.FECHA_FIN,
                EQUIPOS.NOM_EQUIPO, STAFFS.NOMBRE
);

-- BORRADO Y CREACION DE SINONIMOS.

DROP SYNONYM ENFREN;
DROP SYNONYM PATRO_EQUI;
DROP SYNONYM EQUI_COMPE;
DROP SYNONYM INFO_COMPE;
DROP SYNONYM INFO_EQUI;

-- Sinonimos para algunas tablas:
CREATE PUBLIC SYNONYM ENFREN
FOR eqdaw03.ENFRENTAMIENTOS;

CREATE PUBLIC SYNONYM PATRO_EQUI
FOR eqdaw03.PATROCINADORES_EQUIPOS;

CREATE PUBLIC SYNONYM EQUI_COMPE
FOR eqdaw03.EQUIPOS_COMPETICIONES;

-- Sinonimos para los procedimientos:
CREATE PUBLIC SYNONYM INFO_COMPE
FOR eqdaw03.OBTENER_INFO_COMPETICION;

CREATE PUBLIC SYNONYM INFO_EQUI
FOR eqdaw03.OBTENER_INFORMACION;
