-- 1. Script SQL de borrado y creación de las vistas y sinónimos.

-- Comprobación de los datos de las tablas.
SELECT * FROM USUARIO;
SELECT * FROM JUGADOR;
SELECT * FROM STAFF;
SELECT * FROM EQUIPO;
SELECT * FROM PATROCINADOR;
SELECT * FROM COMPETICION;
SELECT * FROM JORNADA;
SELECT * FROM ENFRENTAMIENTO;
SELECT * FROM JUEGO;
SELECT * FROM PATROCINADOR_EQUIPO;
SELECT * FROM EQUIPO_COMPETICION;

-- BORRADO Y CREACIÓN DE VISTAS.

-- Select que devuelve todos los jugadores con sus equipos correspondientes.
CREATE OR REPLACE VIEW VISTA_JUGADORES_EQUIPOS AS (
	SELECT J.ID_JUGADOR, J.NOMBRE, J.NICKNAME, J.NACIONALIDAD, E.ID_EQUIPO,
            E.NOM_EQUIPO
	FROM JUGADOR J, EQUIPO E
	WHERE E.ID_EQUIPO = J.ID_EQUIPO
);

-- Select que devuelve los enfrentamientos que hay por jornada en una competición.
CREATE OR REPLACE VIEW VISTA_ENFRENTAMIENTOS_JORNADA AS (
	SELECT  E.ID_ENFRENTAMIENTO, E.HORA_ENFRENTAMIENTO, E.RESULTADO1 AS "RESULTADO_EQUIPO_1",
            E.RESULTADO2 AS "RESULTADO_EQUIPO_2", J.ID_JORNADA, J.FECHA_JORNADA, C.ID_COMPETICION,
            C.NOMBRE_COM AS "NOMBRE_COMPETICION"
	FROM ENFRENTAMIENTO E, JORNADA J, COMPETICION C
	WHERE E.ID_JORNADA = J.ID_JORNADA
    AND J.ID_COMPETICION = C.ID_COMPETICION
    GROUP BY E.ID_ENFRENTAMIENTO, E.HORA_ENFRENTAMIENTO, J.ID_JORNADA, C.ID_COMPETICION
);

/*
Relación de los equipos que conforman la competición en un momento determinado,
con todos los datos que se tengan de la misma: nombre del juego, fechas, relación
de equipos incluyendo para cada equipo el nombre del mismo, los miembros del
staff y la cantidad de jugadores que hay en ese equipo.
*/
CREATE OR REPLACE VIEW VISTA_EQUIPOS_COMPETICION AS (
	SELECT JUEGO.NOMBRE AS "NOMBRE_JUEGO", COMPETICION.FECHA_INICIO,
            COMPETICION.FECHA_FIN, EQUIPO.NOM_EQUIPO AS "NOMBRE_EQUIPO",
            STAFF.NOMBRE AS "NOMBRE_STAFF",
            COUNT(JUGADOR.ID_JUGADOR) AS "NUMERO_JUGADORES"
    FROM EQUIPO
    JOIN STAFF ON EQUIPO.ID_EQUIPO = STAFF.ID_EQUIPO
    JOIN EQUIPO_COMPETICION ON EQUIPO.ID_EQUIPO = EQUIPO_COMPETICION.ID_EQUIPO
    JOIN COMPETICION
        ON EQUIPO_COMPETICION.ID_COMPETICION = COMPETICION.ID_COMPETICION
    JOIN JUEGO ON COMPETICION.ID_JUEGO = JUEGO.ID_JUEGO
    LEFT JOIN JUGADOR ON EQUIPO.ID_EQUIPO = JUGADOR.ID_EQUIPO
    GROUP BY JUEGO.NOMBRE, COMPETICION.FECHA_INICIO, COMPETICION.FECHA_FIN,
                EQUIPO.NOM_EQUIPO, STAFF.NOMBRE
);

-- BORRADO Y CREACIÓN DE SINÓNIMOS.

DROP SYNONYM XML_C;
DROP SYNONYM XML_T;
DROP SYNONYM XML_U;

CREATE SYNONYM XML_C
FOR eqdaw03.XML_CLASIFICACION;

CREATE SYNONYM XML_T
FOR eqdaw03.XML_TODASJORNADAS;

CREATE SYNONYM XML_U
FOR eqdaw03.XML_ULTIMAJORNADA;


-- CONFIRMACI�N FINAL.
COMMIT;