/*Equipos*/

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Fnatic', TO_DATE('23-06-2004', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'G2', TO_DATE('25-02-2014', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'KOI', TO_DATE('15-12-2021', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'FaZe Clan', TO_DATE('30-05-2010', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Mad Lions', TO_DATE('31-08-2017', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'T1', TO_DATE('30-09-2002', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'OG', TO_DATE('31-10-2015', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('09-09-2000', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team SoloMid', TO_DATE('15-09-2009', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'NAVI', TO_DATE('18-12-2009', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Evil Geniuses', TO_DATE('28-05-1999', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Astralis', TO_DATE('18-01-2016', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, '100 Thieves', TO_DATE('04-11-2017', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team Vitality', TO_DATE('01-12-2015', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Rogue', TO_DATE('07-05-2016', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Virtus.pro', TO_DATE('29-12-2003', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team Envy', TO_DATE('10-02-2007', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Gen.G Esports', TO_DATE('17-04-2017', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team Secret', TO_DATE('11-08-2014', 'DD-MM-YYYY'));

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'FlyQuest', TO_DATE('06-01-2017', 'DD-MM-YYYY'));