/* Insert de equipos */

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/team-liquid-logo.png?raw=true', '#091623');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/fnatic-logo.png?raw=true', '#ff5900');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Evil Geniuses', TO_DATE('21-03-2005', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/evil-geniuses-gc-logo.png?raw=true', '#f3eddf');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Cloud9', TO_DATE('30-08-2006', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/cloud9-logo.png?raw=true', '#0096e1');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'G2 Esports', TO_DATE('12-05-2009', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/g2-esports-logo.png?raw=true', '#ffffff');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'T1', TO_DATE('17-11-2010', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/t1-academy-logo.png?raw=true', '#e2012d');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'FaZe Clan', TO_DATE('05-06-2010', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/faze-clan-logo.png?raw=true', '#e43d2f');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team SoloMid (TSM)', TO_DATE('15-02-2011', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/team-solomid-logo.png?raw=true', '#ffffff');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Natus Vincere (Na Vi)', TO_DATE('28-04-2012', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/natus-vincere-celestials-logo.png?raw=true', '#ffed00');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Astralis', TO_DATE('08-09-2013', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/astralis-logo.png?raw=true', '#ef3742');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Vitality', TO_DATE('19-03-2014', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/vitality.bee-logo.png?raw=true', '#fdc32e');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Envy', TO_DATE('27-10-2014', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/team-envyus-logo.png?raw=true', '#192f61');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Rogue', TO_DATE('14-06-2015', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/rogue-esports-club-logo.png?raw=true', '#2d97d3');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Dignitas', TO_DATE('09-01-2016', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/dignitas-logo.png?raw=true', '#ffcd00');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, '100 Thieves', TO_DATE('22-08-2016', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/100-thieves-logo.png?raw=true', '#ea3232');

INSERT INTO EQUIPOS (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Gen.G Esports', TO_DATE('03-04-2017', 'DD-MM-YYYY'),
       'https://github.com/IbaiSaenzDeBuruaga/E-SportsLogos/blob/main/gen.g-logo.png?raw=true', '#a48721');


/* Insert de jugadores */

/* Equipo 1 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('loyalty', 'GarotaWarr', 'Alemania',
        'Lider', TO_DATE('07-06-1990', 'DD-MM-YYYY'), 1881.61, 1);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('rubia', 'zito585', 'Brasil',
        'Jugador', TO_DATE('07-01-1991', 'DD-MM-YYYY'), 1600.36, 1);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('darcella', 'senpai_mxddy', 'Argentina',
        'Jugador', TO_DATE('10-04-1997', 'DD-MM-YYYY'), 1754.73, 1);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('alem', 'ItzElias_MC', 'Canadá',
        'Jugador', TO_DATE('04-05-1998', 'DD-MM-YYYY'), 1864.74, 1);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tomekia', 'KaiPanda88', 'Canadá',
        'Jugador', TO_DATE('23-07-1995', 'DD-MM-YYYY'), 1730.85, 1);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('claire', 'Jannus37', 'Reino Unido',
        'Jugador', TO_DATE('10-08-2004', 'DD-MM-YYYY'), 1788.64, 1);

/* Equipo 2 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('saniyya', 'itay_rap', 'India',
        'Lider', TO_DATE('19-04-1995', 'DD-MM-YYYY'), 2278.33, 2);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('anvi', 'HeyItsBreeee', 'India',
        'Jugador', TO_DATE('17-02-2000', 'DD-MM-YYYY'), 2481.34, 2);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dashanti', 'iArad', 'Corea del Sur',
        'Jugador', TO_DATE('08-05-1997', 'DD-MM-YYYY'), 1699.74, 2);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('wisdom', 'Nodhulos', 'Francia',
        'Jugador', TO_DATE('22-12-2004', 'DD-MM-YYYY'), 2237.3, 2);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tunisha', 'KayX23', 'Corea del Sur',
        'Jugador', TO_DATE('20-12-2005', 'DD-MM-YYYY'), 1534.39, 2);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('zyann', 'jedman503', 'Canadá',
        'Jugador', TO_DATE('28-10-1992', 'DD-MM-YYYY'), 1547.28, 2);

/* Equipo 3 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('caitlynn', 'AnnyDash', 'Argentina',
        'Lider', TO_DATE('25-08-2004', 'DD-MM-YYYY'), 2231.68, 3);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('christene', 'shadowking320', 'Australia',
        'Jugador', TO_DATE('29-12-1999', 'DD-MM-YYYY'), 2122.92, 3);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('levita', 'EnderHypeZz', 'Argentina',
        'Jugador', TO_DATE('20-10-1997', 'DD-MM-YYYY'), 2157.1, 3);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jaclin', 'cdogg1999', 'China',
        'Jugador', TO_DATE('13-11-1992', 'DD-MM-YYYY'), 1699.77, 3);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('velicia', 'helikid313', 'Japón',
        'Jugador', TO_DATE('29-06-2002', 'DD-MM-YYYY'), 2153.88, 3);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('destin', 'haloc14', 'Argentina',
        'Jugador', TO_DATE('08-11-1994', 'DD-MM-YYYY'), 1686.17, 3);

/* Equipo 4 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('chianne', 'Kiwax_', 'India',
        'Lider', TO_DATE('03-01-2006', 'DD-MM-YYYY'), 2140.63, 4);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('palyn', 'SillyDillyPickle', 'Reino Unido',
        'Jugador', TO_DATE('13-05-2002', 'DD-MM-YYYY'), 1719.04, 4);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jayonna', 'Zouxq', 'Estados Unidos',
        'Jugador', TO_DATE('08-05-1997', 'DD-MM-YYYY'), 1989.34, 4);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('nayomi', 'QRGAMER10', 'Japón',
        'Jugador', TO_DATE('21-06-1989', 'DD-MM-YYYY'), 1587.84, 4);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('annalucia', 'Fanji24', 'India',
        'Jugador', TO_DATE('10-03-1995', 'DD-MM-YYYY'), 1925.33, 4);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('mykell', 'JayySea', 'Italia',
        'Jugador', TO_DATE('27-07-1992', 'DD-MM-YYYY'), 1997.93, 4);

/* Equipo 5 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kortny', 'CommandoPee', 'Italia',
        'Lider', TO_DATE('05-05-2004', 'DD-MM-YYYY'), 1924.72, 5);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('yovanny', 'Apatheticpikachu', 'Italia',
        'Jugador', TO_DATE('20-06-1991', 'DD-MM-YYYY'), 1873.65, 5);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('arshad', 'EpikJoker', 'México',
        'Jugador', TO_DATE('27-11-2002', 'DD-MM-YYYY'), 1922.7, 5);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jenay', 'Matt6288', 'Alemania',
        'Jugador', TO_DATE('12-11-1997', 'DD-MM-YYYY'), 2399.98, 5);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('daziyah', 'TheOnlyBae', 'Estados Unidos',
        'Jugador', TO_DATE('16-04-2000', 'DD-MM-YYYY'), 2479.54, 5);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('antonina', 'FyrePowrHD', 'China',
        'Jugador', TO_DATE('07-06-2000', 'DD-MM-YYYY'), 1521.1, 5);

/* Equipo 6 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('coady', 'Sorogon_', 'Estados Unidos',
        'Lider', TO_DATE('17-12-2003', 'DD-MM-YYYY'), 1514.29, 6);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dunia', 'DanielStatzz', 'México',
        'Jugador', TO_DATE('22-11-1999', 'DD-MM-YYYY'), 2071.82, 6);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('levante', 'KillinSpreeFull', 'Canadá',
        'Jugador', TO_DATE('23-01-1992', 'DD-MM-YYYY'), 2378.88, 6);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tyquez', 'CupcakeMixer', 'Brasil',
        'Jugador', TO_DATE('27-06-2005', 'DD-MM-YYYY'), 2157.53, 6);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('faisal', 'TaylorIsTheQueen', 'Reino Unido',
        'Jugador', TO_DATE('19-07-1995', 'DD-MM-YYYY'), 2290.02, 6);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('mareli', 'mrswapers', 'Japón',
        'Jugador', TO_DATE('21-12-2001', 'DD-MM-YYYY'), 1987.97, 6);

/* Equipo 7 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kailee', 'sharx_and_scones', 'Estados Unidos',
        'Lider', TO_DATE('31-05-1998', 'DD-MM-YYYY'), 2024.84, 7);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('vivyana', 'Alli1003g', 'India',
        'Jugador', TO_DATE('26-07-2003', 'DD-MM-YYYY'), 2341.25, 7);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('braxson', 'Boxtel', 'Italia',
        'Jugador', TO_DATE('08-03-1994', 'DD-MM-YYYY'), 2202.53, 7);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('aibhlinn', 'XxEvilMonkeyxX', 'Argentina',
        'Jugador', TO_DATE('29-11-1989', 'DD-MM-YYYY'), 2495.75, 7);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('ilah', 'camunlucas', 'Reino Unido',
        'Jugador', TO_DATE('15-02-1994', 'DD-MM-YYYY'), 2235.92, 7);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jaselynn', 'JarneMisionX1', 'Rusia',
        'Jugador', TO_DATE('07-02-1998', 'DD-MM-YYYY'), 2174.41, 7);

/* Equipo 8 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jurgen', 'Arduinos', 'Alemania',
        'Lider', TO_DATE('18-05-2002', 'DD-MM-YYYY'), 1775.07, 8);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dorinda', 'KingBraden04', 'Australia',
        'Jugador', TO_DATE('20-08-2000', 'DD-MM-YYYY'), 1853.66, 8);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gidget', 'NotYourAvgCactus', 'Australia',
        'Jugador', TO_DATE('31-01-1990', 'DD-MM-YYYY'), 2057.78, 8);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('janyia', 'Lemonaise', 'Alemania',
        'Jugador', TO_DATE('30-04-2002', 'DD-MM-YYYY'), 2039.96, 8);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('cyril', 'AshtonMooseSon1', 'México',
        'Jugador', TO_DATE('04-01-2005', 'DD-MM-YYYY'), 2201.57, 8);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('delaynie', 'megnic12', 'Alemania',
        'Jugador', TO_DATE('07-04-1999', 'DD-MM-YYYY'), 2146.73, 8);

/* Equipo 9 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jasani', 'ktstew', 'Estados Unidos',
        'Lider', TO_DATE('25-07-1992', 'DD-MM-YYYY'), 2055.94, 9);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('briggitte', 'YUDORA', 'Corea del Sur',
        'Jugador', TO_DATE('22-01-1999', 'DD-MM-YYYY'), 1888.4, 9);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('nanami', 'RedstoneGenius45', 'México',
        'Jugador', TO_DATE('04-02-2004', 'DD-MM-YYYY'), 2200.35, 9);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('athena', 'jalden99', 'Brasil',
        'Jugador', TO_DATE('05-09-2004', 'DD-MM-YYYY'), 1745.34, 9);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('arreon', 'xX_PotatoWolf_Xx', 'Australia',
        'Jugador', TO_DATE('22-04-1994', 'DD-MM-YYYY'), 1953.4, 9);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('anessa', 'PyreYT', 'India',
        'Jugador', TO_DATE('26-04-2001', 'DD-MM-YYYY'), 1598.96, 9);

/* Equipo 10 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('solanch', 'Minpyttekat', 'Japón',
        'Lider', TO_DATE('30-06-2005', 'DD-MM-YYYY'), 2147.33, 10);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('nylia', 'Flo2009', 'Argentina',
        'Jugador', TO_DATE('06-07-1999', 'DD-MM-YYYY'), 2494.76, 10);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('marty', 'makarg7', 'Canadá',
        'Jugador', TO_DATE('11-05-1992', 'DD-MM-YYYY'), 1563.68, 10);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('meliya', 'xMazHD1997', 'China',
        'Jugador', TO_DATE('11-10-1991', 'DD-MM-YYYY'), 1640.23, 10);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('shakura', 'Penguin_head', 'India',
        'Jugador', TO_DATE('04-06-1992', 'DD-MM-YYYY'), 1541.1, 10);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('sanjaya', 'DTZ_David', 'India',
        'Jugador', TO_DATE('11-05-2002', 'DD-MM-YYYY'), 1726.51, 10);

/* Equipo 11 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('twan', 'Paje_PVP', 'Japón',
        'Lider', TO_DATE('03-10-2003', 'DD-MM-YYYY'), 2215.35, 11);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('davian', 'SHOCKINGSHEEP', 'Japón',
        'Jugador', TO_DATE('05-08-1996', 'DD-MM-YYYY'), 1771.39, 11);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tresia', 'SE16N', 'Alemania',
        'Jugador', TO_DATE('24-11-1994', 'DD-MM-YYYY'), 2267.25, 11);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('ameera', 'RobBarg', 'Australia',
        'Jugador', TO_DATE('25-06-1998', 'DD-MM-YYYY'), 2400.31, 11);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('ameris', 'ZeadGod', 'Canadá',
        'Jugador', TO_DATE('03-06-2001', 'DD-MM-YYYY'), 1523.07, 11);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('taronda', 'CharSnake', 'Argentina',
        'Jugador', TO_DATE('07-01-1993', 'DD-MM-YYYY'), 1929.2, 11);

/* Equipo 12 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gaddiel', 'rezakaJDM', 'Corea del Sur',
        'Lider', TO_DATE('05-12-1994', 'DD-MM-YYYY'), 2236.92, 12);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('maika', 'AdriaNPlays46', 'Corea del Sur',
        'Jugador', TO_DATE('09-05-2002', 'DD-MM-YYYY'), 2165.71, 12);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('caspian', 'BasicPvP', 'Corea del Sur',
        'Jugador', TO_DATE('15-04-1994', 'DD-MM-YYYY'), 1888.16, 12);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('neta', 'RedRevengers', 'Reino Unido',
        'Jugador', TO_DATE('23-01-1991', 'DD-MM-YYYY'), 1761.0, 12);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tanzie', 'sharksfood', 'Rusia',
        'Jugador', TO_DATE('15-10-1990', 'DD-MM-YYYY'), 1559.56, 12);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dolan', 'Budilein', 'Japón',
        'Jugador', TO_DATE('22-06-1994', 'DD-MM-YYYY'), 2067.7, 12);

/* Equipo 13 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gill', 'FatToddler', 'México',
        'Lider', TO_DATE('15-09-2000', 'DD-MM-YYYY'), 2352.97, 13);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jilda', 'KittKatt0', 'Corea del Sur',
        'Jugador', TO_DATE('26-11-1994', 'DD-MM-YYYY'), 1833.86, 13);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('marlana', 'CombatCutie', 'Brasil',
        'Jugador', TO_DATE('29-04-1991', 'DD-MM-YYYY'), 2163.97, 13);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('wilfrido', 'IanDW1', 'Reino Unido',
        'Jugador', TO_DATE('21-08-2000', 'DD-MM-YYYY'), 1779.39, 13);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dyonna', 'Blique', 'Rusia',
        'Jugador', TO_DATE('11-08-2001', 'DD-MM-YYYY'), 2090.9, 13);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('hoda', 'Hippos', 'China',
        'Jugador', TO_DATE('24-06-2002', 'DD-MM-YYYY'), 1639.79, 13);

/* Equipo 14 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jadynn', 'kirito7416', 'Australia',
        'Lider', TO_DATE('24-08-1995', 'DD-MM-YYYY'), 2313.01, 14);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('irfan', 'PieOrPi', 'Alemania',
        'Jugador', TO_DATE('23-04-1993', 'DD-MM-YYYY'), 2449.83, 14);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('cheralyn', 'CutieAna', 'Corea del Sur',
        'Jugador', TO_DATE('23-07-2000', 'DD-MM-YYYY'), 1866.12, 14);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('aliviya', 'MarbleCandy', 'Reino Unido',
        'Jugador', TO_DATE('05-08-1993', 'DD-MM-YYYY'), 1651.92, 14);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jenisis', 'Agnios', 'Australia',
        'Jugador', TO_DATE('24-03-2000', 'DD-MM-YYYY'), 1802.62, 14);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('leara', 'IKnowImAWolf', 'Japón',
        'Jugador', TO_DATE('16-02-1995', 'DD-MM-YYYY'), 2064.06, 14);

/* Equipo 15 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lanisha', 'SaintClairee', 'Canadá',
        'Lider', TO_DATE('26-06-1999', 'DD-MM-YYYY'), 2257.82, 15);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dorathy', 'Brrokk', 'Rusia',
        'Jugador', TO_DATE('24-12-1997', 'DD-MM-YYYY'), 2323.71, 15);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('cortney', 'ThisHorseGirl', 'Australia',
        'Jugador', TO_DATE('11-12-1997', 'DD-MM-YYYY'), 1777.8, 15);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kirklan', 'chris129', 'Argentina',
        'Jugador', TO_DATE('09-08-2001', 'DD-MM-YYYY'), 1527.16, 15);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('teresea', 'mustashman7878', 'Rusia',
        'Jugador', TO_DATE('18-10-1993', 'DD-MM-YYYY'), 1535.77, 15);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('shelsy', 'Gev_Blackings', 'China',
        'Jugador', TO_DATE('20-10-1990', 'DD-MM-YYYY'), 2127.46, 15);

/* Equipo 16 */
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('paullette', 'deantaylor2015', 'Estados Unidos',
        'Lider', TO_DATE('01-12-1994', 'DD-MM-YYYY'), 2026.82, 16);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('levar', 'OMGAtomicPenguin', 'Reino Unido',
        'Jugador', TO_DATE('02-05-2006', 'DD-MM-YYYY'), 1988.44, 16);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('karington', 'Twistxz', 'Alemania',
        'Jugador', TO_DATE('19-03-2002', 'DD-MM-YYYY'), 1807.38, 16);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('mamadou', 'yummy_suqirtz', 'India',
        'Jugador', TO_DATE('25-11-1996', 'DD-MM-YYYY'), 1563.64, 16);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('vivaan', 'XxLunaGurlxX', 'México',
        'Jugador', TO_DATE('26-10-1996', 'DD-MM-YYYY'), 1863.18, 16);
INSERT INTO JUGADORES
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('towanda', 'FunStyle08', 'Estados Unidos',
        'Jugador', TO_DATE('13-11-1990', 'DD-MM-YYYY'), 1803.19, 16);


/* Insert de staff */

/* Staff equipo 1 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'bellina',
TO_DATE('15-03-1999', 'DD-MM-YYYY'), 2384.39, 1);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'michael',
TO_DATE('25-12-1985', 'DD-MM-YYYY'), 2553.14, 1);

/* Staff equipo 2 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'phillippa',
TO_DATE('03-11-1980', 'DD-MM-YYYY'), 4355.37, 2);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'juliahna',
TO_DATE('06-09-1969', 'DD-MM-YYYY'), 1098.32, 2);

/* Staff equipo 3 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'brenda',
TO_DATE('09-09-1994', 'DD-MM-YYYY'), 2363.13, 3);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'keshauna',
TO_DATE('18-02-1993', 'DD-MM-YYYY'), 2283.32, 3);

/* Staff equipo 4 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'anik',
TO_DATE('14-07-1964', 'DD-MM-YYYY'), 4691.98, 4);

/* Staff equipo 5 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'arneisha',
TO_DATE('18-02-1991', 'DD-MM-YYYY'), 2794.82, 5);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'myrtle',
TO_DATE('19-11-1980', 'DD-MM-YYYY'), 1256.81, 5);

/* Staff equipo 6 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'bane',
TO_DATE('18-12-1967', 'DD-MM-YYYY'), 3167.37, 6);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'kourosh',
TO_DATE('31-12-1965', 'DD-MM-YYYY'), 2251.47, 6);

/* Staff equipo 7 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'zarielle',
TO_DATE('14-06-1985', 'DD-MM-YYYY'), 2688.01, 7);

/* Staff equipo 8 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'jennavicia',
TO_DATE('29-10-1983', 'DD-MM-YYYY'), 4656.15, 8);
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'A', 'kaseem',
TO_DATE('12-11-1964', 'DD-MM-YYYY'), 2320.28, 8);

/* Staff equipo 9 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'collis',
TO_DATE('31-07-1970', 'DD-MM-YYYY'), 2295.21, 9);

/* Staff equipo 10 */
INSERT INTO STAFFS
(ID_STAFF, PUESTO, NOMBRE, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES (DEFAULT, 'E', 'raizy',
TO_DATE('07-02-2003', 'DD-MM-YYYY'), 3608.53, 10);


/* Insert de patrocinadores */

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Zhejiang Materials Industry Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Korea Electric Power');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Louis Dreyfus Commodities');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Lufthansa Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Huawei Investment and Holding');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China National Bldg. Materials Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sberbank');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'National Grid');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Jardine Matheson');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Wilmar International');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sony');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Michelin');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Deutsche Telekom');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China Nonferrous Metal Mining');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China Shipbuilding Industry');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Microsoft');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'McKesson');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Verizon');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Avnet');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'AntarChile');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'ACS');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China Electronics');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'UBS Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Shandong Energy Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Bank of America Corp.');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Prudential Financial');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Iberdrola');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Novartis');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Samsung Electronics');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'America Movil');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China Huadian');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sumitomo');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'McDonalds');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Shenhua Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Baosteel Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Achmea');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Bank of Nova Scotia');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Coop Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sinochem');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'LG Display');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'RWE');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sinopec Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Johnson Controls');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Mazda Motor');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'PDVSA');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'POSCO');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'JFE Holdings');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Fannie Mae');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Lowes');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Kroger');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Samsung Life Insurance');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Zhejiang Geely Holding Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'World Fuel Services');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Telecom Italia');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Royal Ahold');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Petronas');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Suzuki Motor');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Banco Santander');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Unilever');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Henan Energy and Chemical');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sompo Japan Nipponkoa');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'ABB');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'AEON');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'JX Holdings');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China FAW Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Japan Post Holdings');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Vinci');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Panasonic');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Finatis');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Fujitsu');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Standard Chartered');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'ThyssenKrupp');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Banco do Brasil');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China Post Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Datong Coal Mine Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Telstra');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China General Technology');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Plains GP Holdings');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Boeing');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sharp');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'BP');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Greenland Holding Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Deutsche Post');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Legal and General Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'SoftBank Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'BNP Paribas');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Express Scripts Holding');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Enbridge');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'China National Aviation Fuel Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Saint-Gobain');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Baker Hughes');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Peugeot');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Sainsburys');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Idemitsu Kosan');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Bank of China');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Tata Motors');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Beijing Automotive Group');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'State Farm Insurance Cos.');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'GDF Suez');

INSERT INTO PATROCINADORES (ID_PATROCINADOR, NOMBRE)
VALUES (DEFAULT, 'Dai-ichi Life Insurance');


/* Insert de enlaces entre patrocinadores y equipos */

/* Patrocinadores equipo 1 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (7, 1);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (12, 1);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (19, 1);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (2, 1);

/* Patrocinadores equipo 2 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (10, 2);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (2, 2);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (16, 2);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (11, 2);

/* Patrocinadores equipo 3 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (7, 3);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (5, 3);

/* Patrocinadores equipo 4 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (4, 4);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (6, 4);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (16, 4);

/* Patrocinadores equipo 5 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (7, 5);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (4, 5);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (17, 5);

/* Patrocinadores equipo 6 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (14, 6);

/* Patrocinadores equipo 7 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (7, 7);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (3, 7);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (15, 7);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (19, 7);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (17, 7);

/* Patrocinadores equipo 8 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (17, 8);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (19, 8);

/* Patrocinadores equipo 9 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (1, 9);

/* Patrocinadores equipo 10 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (19, 10);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (13, 10);

/* Patrocinadores equipo 11 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (16, 11);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (10, 11);

/* Patrocinadores equipo 12 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (18, 12);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (15, 12);

/* Patrocinadores equipo 13 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (2, 13);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (16, 13);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (14, 13);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (18, 13);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (19, 13);

/* Patrocinadores equipo 14 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (3, 14);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (15, 14);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (7, 14);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (14, 14);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (1, 14);

/* Patrocinadores equipo 15 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (3, 15);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (11, 15);
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (16, 15);

/* Patrocinadores equipo 16 */
INSERT INTO PATROCINADORES_EQUIPOS (ID_PATROCINADOR, ID_EQUIPO)
VALUES (10, 16);


/* Insert de juegos */

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Doom', 'id Software', 
TO_DATE('13-07-2021', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Quake', 'id Software', 
TO_DATE('08-09-2008', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Counter-Strike series', 'Valve', 
TO_DATE('10-05-1995', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Call of Duty series', 'Infinity Ward, Treyarch, Sledgehammer Games, entre otros.', 
TO_DATE('07-12-2024', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Unreal Tournament', 'Epic Games', 
TO_DATE('24-06-2020', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Halo series', 'Bungie Studios, 343 Industries (subsidiaria de Microsoft Studios)', 
TO_DATE('08-12-2007', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Painkiller', 'People Can Fly, DreamCatcher Interactive', 
TO_DATE('11-04-1992', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Battlefield series', 'DICE (subsidiaria de Electronic Arts)', 
TO_DATE('18-06-1990', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Overwatch', 'Blizzard Entertainment', 
TO_DATE('18-04-1996', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Team Fortress 2', 'Valve Corporation', 
TO_DATE('27-06-2009', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Rainbow Six: Siege', 'Ubisoft', 
TO_DATE('25-06-1992', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Valorant', 'Riot Games', 
TO_DATE('24-10-2005', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'League of Legends', 'Riot Games', 
TO_DATE('07-02-1995', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Dota 2', 'Valve Corporation', 
TO_DATE('27-08-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Smite', 'Hi-Rez Studios', 
TO_DATE('15-08-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Heroes of the Storm', 'Blizzard Entertainment', 
TO_DATE('18-10-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Vainglory', 'Super Evil Megacorp', 
TO_DATE('02-09-2024', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Arena of Valor', 'TiMi Studios (desarrollador), Tencent Games (publicador)', 
TO_DATE('16-10-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Mobile Legends: Bang Bang', 'Moonton', 
TO_DATE('26-03-1994', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Formula 1 official games', 'Codemasters', 
TO_DATE('02-12-2011', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Gran Turismo Sport', 'Polyphony Digital (desarrollador), Sony Interactive Entertainment (publicador)', 
TO_DATE('10-11-1993', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'iRacing', 'iRacing.com Motorsport Simulations', 
TO_DATE('07-11-2024', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Trackmania', 'Nadeo (desarrollador), Ubisoft (publicador)', 
TO_DATE('21-02-1996', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Project CARS', 'Slightly Mad Studios (desarrollador), Bandai Namco Entertainment (publicador)', 
TO_DATE('28-03-2009', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'rFactor 2', 'Studio 397', 
TO_DATE('07-08-1995', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Kart Rider', 'Nexon', 
TO_DATE('03-02-2017', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'StarCraft', 'Blizzard Entertainment', 
TO_DATE('02-07-2024', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'StarCraft II', 'Blizzard Entertainment', 
TO_DATE('20-06-2002', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Warcraft III', 'Blizzard Entertainment', 
TO_DATE('25-03-1993', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'FIFA Football', 'Electronic Arts', 
TO_DATE('23-11-2022', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Madden NFL', 'Electronic Arts', 
TO_DATE('15-03-1998', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'NBA 2K', 'Take-Two Interactive', 
TO_DATE('10-02-1993', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Pro Evolution Soccer', 'Konami', 
TO_DATE('10-03-2015', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Street Fighter', 'Capcom', 
TO_DATE('08-10-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Super Smash Bros.', 'Nintendo', 
TO_DATE('13-11-2021', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Marvel vs. Capcom', 'Capcom', 
TO_DATE('21-04-2006', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Tekken', 'Bandai Namco', 
TO_DATE('10-04-2022', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Killer Instinct', 'Microsoft', 
TO_DATE('02-02-1994', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Rocket League', 'Psyonix Studios', 
TO_DATE('16-06-2010', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Gears of War', 'The Coalition', 
TO_DATE('02-06-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'PlayerUnknowns Battlegrounds (PUBG)', 'PUBG Corporation', 
TO_DATE('07-01-2019', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Garena Free Fire', '111dots Studio (desarrollador), Garena (publicador)', 
TO_DATE('11-04-1990', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Splatoon 2', 'Nintendo', 
TO_DATE('25-08-2005', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Hearthstone', 'Blizzard Entertainment', 
TO_DATE('25-12-1991', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Shadowverse', 'Cygames', 
TO_DATE('20-07-2000', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Magic: The Gathering Arena', 'Wizards of the Coast', 
TO_DATE('06-03-2023', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Pokemon', 'The Pokemon Company', 
TO_DATE('26-06-1993', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Puyo Puyo', 'Sega', 
TO_DATE('21-01-1997', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Clash Royale', 'Supercell', 
TO_DATE('20-01-1997', 'DD-MM-YYYY'));

INSERT INTO JUEGOS (ID_JUEGO, NOMBRE, EMPRESA, FECHA_LANZAMIENTO)
VALUES (DEFAULT, 'Clash of Clans', 'Supercell', 
TO_DATE('10-09-2000', 'DD-MM-YYYY'));


/* Competición 1 */

INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE_COM, FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
        TO_DATE('05-05-2024', 'DD-MM-YYYY'), 
        TO_DATE('05-05-2025', 'DD-MM-YYYY'), 'A', 3, NULL);

/* Equipos competición 1 */
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (2, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (9, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (5, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (6, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (7, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (10, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (1, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (8, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (3, 1, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (4, 1, 0, 0);

/* Jornadas competición 1 */
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('24-05-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 2, TO_DATE('31-05-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 3, TO_DATE('07-06-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 4, TO_DATE('14-06-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 5, TO_DATE('21-06-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 6, TO_DATE('28-06-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 7, TO_DATE('05-07-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 8, TO_DATE('12-07-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 9, TO_DATE('19-07-2024', 'DD-MM-YYYY'), 1);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 10, TO_DATE('26-07-2024', 'DD-MM-YYYY'), 1);

/* Enfrentamientos competición 1 */
/*Jornada 1*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-05-2024 18:50', 'DD-MM-YYYY HH24:MI'),
1, 3, 1, 13, 1);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-05-2024 14:27', 'DD-MM-YYYY HH24:MI'),
3, 1, 14, 15, 1);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-05-2024 12:18', 'DD-MM-YYYY HH24:MI'),
3, 1, 10, 13, 1);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-05-2024 16:55', 'DD-MM-YYYY HH24:MI'),
3, 1, 3, 10, 1);

/*Jornada 2*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-05-2024 15:33', 'DD-MM-YYYY HH24:MI'),
1, 3, 12, 14, 2);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-05-2024 10:18', 'DD-MM-YYYY HH24:MI'),
3, 2, 13, 7, 2);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-05-2024 13:42', 'DD-MM-YYYY HH24:MI'),
2, 1, 9, 3, 2);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-05-2024 10:33', 'DD-MM-YYYY HH24:MI'),
2, 3, 11, 15, 2);

/*Jornada 3*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-06-2024 18:33', 'DD-MM-YYYY HH24:MI'),
2, 1, 10, 6, 3);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-06-2024 18:05', 'DD-MM-YYYY HH24:MI'),
2, 3, 11, 10, 3);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-06-2024 12:04', 'DD-MM-YYYY HH24:MI'),
1, 3, 9, 14, 3);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-06-2024 12:13', 'DD-MM-YYYY HH24:MI'),
3, 1, 5, 3, 3);

/*Jornada 4*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-06-2024 14:28', 'DD-MM-YYYY HH24:MI'),
3, 1, 6, 5, 4);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-06-2024 18:15', 'DD-MM-YYYY HH24:MI'),
1, 2, 12, 1, 4);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-06-2024 15:10', 'DD-MM-YYYY HH24:MI'),
3, 1, 6, 16, 4);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-06-2024 14:15', 'DD-MM-YYYY HH24:MI'),
2, 1, 16, 6, 4);

/*Jornada 5*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-06-2024 16:59', 'DD-MM-YYYY HH24:MI'),
3, 2, 7, 4, 5);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-06-2024 12:15', 'DD-MM-YYYY HH24:MI'),
2, 1, 16, 2, 5);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-06-2024 16:41', 'DD-MM-YYYY HH24:MI'),
3, 2, 2, 13, 5);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-06-2024 16:53', 'DD-MM-YYYY HH24:MI'),
3, 2, 5, 3, 5);

/*Jornada 6*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('28-06-2024 10:49', 'DD-MM-YYYY HH24:MI'),
2, 3, 13, 6, 6);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('28-06-2024 17:19', 'DD-MM-YYYY HH24:MI'),
1, 2, 1, 10, 6);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('28-06-2024 18:16', 'DD-MM-YYYY HH24:MI'),
1, 3, 6, 3, 6);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('28-06-2024 16:26', 'DD-MM-YYYY HH24:MI'),
2, 1, 7, 3, 6);

/*Jornada 7*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('05-07-2024 10:37', 'DD-MM-YYYY HH24:MI'),
2, 1, 5, 2, 7);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('05-07-2024 17:45', 'DD-MM-YYYY HH24:MI'),
3, 2, 1, 5, 7);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('05-07-2024 16:34', 'DD-MM-YYYY HH24:MI'),
2, 1, 5, 11, 7);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('05-07-2024 17:44', 'DD-MM-YYYY HH24:MI'),
2, 3, 16, 11, 7);

/*Jornada 8*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('12-07-2024 11:14', 'DD-MM-YYYY HH24:MI'),
2, 3, 2, 9, 8);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('12-07-2024 17:31', 'DD-MM-YYYY HH24:MI'),
2, 3, 14, 4, 8);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('12-07-2024 13:07', 'DD-MM-YYYY HH24:MI'),
3, 1, 5, 7, 8);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('12-07-2024 14:22', 'DD-MM-YYYY HH24:MI'),
3, 1, 1, 14, 8);

/*Jornada 9*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('19-07-2024 17:38', 'DD-MM-YYYY HH24:MI'),
1, 2, 5, 8, 9);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('19-07-2024 14:18', 'DD-MM-YYYY HH24:MI'),
2, 1, 16, 9, 9);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('19-07-2024 13:01', 'DD-MM-YYYY HH24:MI'),
2, 1, 10, 6, 9);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('19-07-2024 16:40', 'DD-MM-YYYY HH24:MI'),
2, 1, 1, 12, 9);

/*Jornada 10*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('26-07-2024 10:34', 'DD-MM-YYYY HH24:MI'),
3, 1, 6, 10, 10);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('26-07-2024 12:11', 'DD-MM-YYYY HH24:MI'),
1, 3, 15, 5, 10);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('26-07-2024 17:12', 'DD-MM-YYYY HH24:MI'),
2, 1, 8, 5, 10);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('26-07-2024 11:02', 'DD-MM-YYYY HH24:MI'),
1, 3, 9, 7, 10);


/* Competición 2 */

INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE_COM, FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'LEC', 
        TO_DATE('01-01-2025', 'DD-MM-YYYY'), 
        TO_DATE('01-01-2026', 'DD-MM-YYYY'), 'A', 13, NULL);

/* Equipos competición 2 */
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (4, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (9, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (1, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (3, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (6, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (8, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (10, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (5, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (7, 2, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (2, 2, 0, 0);

/* Jornadas competición 2 */
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('24-05-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 2, TO_DATE('31-05-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 3, TO_DATE('07-06-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 4, TO_DATE('14-06-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 5, TO_DATE('21-06-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 6, TO_DATE('28-06-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 7, TO_DATE('05-07-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 8, TO_DATE('12-07-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 9, TO_DATE('19-07-2025', 'DD-MM-YYYY'), 2);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 10, TO_DATE('26-07-2025', 'DD-MM-YYYY'), 2);

/* Enfrentamientos competición 2 */
/*Jornada 11*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-08-2025 16:34', 'DD-MM-YYYY HH24:MI'),
2, 3, 1, 12, 11);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-08-2025 17:15', 'DD-MM-YYYY HH24:MI'),
3, 2, 15, 9, 11);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-08-2025 13:31', 'DD-MM-YYYY HH24:MI'),
2, 3, 11, 12, 11);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-08-2025 14:59', 'DD-MM-YYYY HH24:MI'),
1, 3, 2, 5, 11);

/*Jornada 12*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('09-08-2025 15:22', 'DD-MM-YYYY HH24:MI'),
3, 1, 2, 13, 12);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('09-08-2025 13:22', 'DD-MM-YYYY HH24:MI'),
2, 3, 8, 11, 12);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('09-08-2025 10:06', 'DD-MM-YYYY HH24:MI'),
3, 1, 11, 15, 12);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('09-08-2025 13:49', 'DD-MM-YYYY HH24:MI'),
1, 3, 6, 7, 12);

/*Jornada 13*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('16-08-2025 17:56', 'DD-MM-YYYY HH24:MI'),
2, 3, 6, 16, 13);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('16-08-2025 18:50', 'DD-MM-YYYY HH24:MI'),
3, 2, 2, 16, 13);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('16-08-2025 17:44', 'DD-MM-YYYY HH24:MI'),
2, 1, 12, 1, 13);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('16-08-2025 16:13', 'DD-MM-YYYY HH24:MI'),
2, 3, 6, 3, 13);

/*Jornada 14*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('23-08-2025 14:44', 'DD-MM-YYYY HH24:MI'),
1, 2, 16, 13, 14);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('23-08-2025 11:02', 'DD-MM-YYYY HH24:MI'),
1, 3, 16, 9, 14);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('23-08-2025 18:55', 'DD-MM-YYYY HH24:MI'),
1, 3, 1, 14, 14);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('23-08-2025 12:36', 'DD-MM-YYYY HH24:MI'),
1, 2, 7, 1, 14);

/*Jornada 15*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('30-08-2025 13:49', 'DD-MM-YYYY HH24:MI'),
2, 3, 4, 13, 15);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('30-08-2025 17:48', 'DD-MM-YYYY HH24:MI'),
3, 1, 4, 2, 15);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('30-08-2025 11:43', 'DD-MM-YYYY HH24:MI'),
1, 2, 13, 3, 15);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('30-08-2025 15:08', 'DD-MM-YYYY HH24:MI'),
1, 3, 14, 8, 15);

/*Jornada 16*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-09-2025 13:06', 'DD-MM-YYYY HH24:MI'),
2, 1, 10, 13, 16);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-09-2025 18:03', 'DD-MM-YYYY HH24:MI'),
2, 1, 8, 15, 16);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-09-2025 17:59', 'DD-MM-YYYY HH24:MI'),
1, 3, 4, 3, 16);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-09-2025 10:35', 'DD-MM-YYYY HH24:MI'),
3, 2, 15, 4, 16);

/*Jornada 17*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-09-2025 16:20', 'DD-MM-YYYY HH24:MI'),
3, 2, 14, 16, 17);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-09-2025 11:19', 'DD-MM-YYYY HH24:MI'),
2, 3, 7, 12, 17);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-09-2025 18:34', 'DD-MM-YYYY HH24:MI'),
1, 3, 4, 15, 17);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-09-2025 10:11', 'DD-MM-YYYY HH24:MI'),
3, 1, 1, 6, 17);

/*Jornada 18*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-09-2025 15:59', 'DD-MM-YYYY HH24:MI'),
2, 1, 10, 14, 18);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-09-2025 15:22', 'DD-MM-YYYY HH24:MI'),
2, 1, 7, 15, 18);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-09-2025 12:31', 'DD-MM-YYYY HH24:MI'),
3, 2, 14, 5, 18);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-09-2025 12:55', 'DD-MM-YYYY HH24:MI'),
2, 1, 7, 1, 18);

/*Jornada 19*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-09-2025 15:14', 'DD-MM-YYYY HH24:MI'),
2, 1, 14, 11, 19);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-09-2025 17:14', 'DD-MM-YYYY HH24:MI'),
2, 1, 7, 6, 19);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-09-2025 16:37', 'DD-MM-YYYY HH24:MI'),
2, 1, 1, 12, 19);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-09-2025 18:52', 'DD-MM-YYYY HH24:MI'),
3, 2, 7, 3, 19);

/*Jornada 20*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('04-10-2025 10:46', 'DD-MM-YYYY HH24:MI'),
2, 1, 14, 2, 20);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('04-10-2025 14:11', 'DD-MM-YYYY HH24:MI'),
2, 3, 10, 8, 20);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('04-10-2025 18:24', 'DD-MM-YYYY HH24:MI'),
1, 3, 9, 14, 20);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('04-10-2025 16:33', 'DD-MM-YYYY HH24:MI'),
3, 2, 10, 9, 20);


/* Competición 3 */

INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE_COM, FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'OWCS 2024', 
        TO_DATE('07-07-2026', 'DD-MM-YYYY'), 
        TO_DATE('07-07-2027', 'DD-MM-YYYY'), 'A', 9, NULL);

/* Equipos competición 3 */
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (1, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (2, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (10, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (5, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (3, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (4, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (6, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (7, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (9, 3, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (8, 3, 0, 0);

/* Jornadas competición 3 */
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('24-05-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 2, TO_DATE('31-05-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 3, TO_DATE('07-06-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 4, TO_DATE('14-06-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 5, TO_DATE('21-06-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 6, TO_DATE('28-06-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 7, TO_DATE('05-07-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 8, TO_DATE('12-07-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 9, TO_DATE('19-07-2026', 'DD-MM-YYYY'), 3);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 10, TO_DATE('26-07-2026', 'DD-MM-YYYY'), 3);

/* Enfrentamientos competición 3 */
/*Jornada 21*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('11-10-2026 15:25', 'DD-MM-YYYY HH24:MI'),
2, 3, 14, 7, 21);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('11-10-2026 13:06', 'DD-MM-YYYY HH24:MI'),
3, 1, 10, 5, 21);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('11-10-2026 18:10', 'DD-MM-YYYY HH24:MI'),
2, 3, 1, 14, 21);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('11-10-2026 12:15', 'DD-MM-YYYY HH24:MI'),
1, 3, 5, 8, 21);

/*Jornada 22*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('18-10-2026 17:55', 'DD-MM-YYYY HH24:MI'),
1, 2, 9, 8, 22);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('18-10-2026 12:02', 'DD-MM-YYYY HH24:MI'),
1, 2, 12, 5, 22);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('18-10-2026 16:08', 'DD-MM-YYYY HH24:MI'),
1, 3, 3, 13, 22);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('18-10-2026 11:19', 'DD-MM-YYYY HH24:MI'),
2, 1, 1, 13, 22);

/*Jornada 23*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('25-10-2026 17:45', 'DD-MM-YYYY HH24:MI'),
2, 3, 7, 3, 23);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('25-10-2026 15:52', 'DD-MM-YYYY HH24:MI'),
2, 3, 9, 12, 23);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('25-10-2026 16:49', 'DD-MM-YYYY HH24:MI'),
2, 1, 16, 10, 23);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('25-10-2026 18:02', 'DD-MM-YYYY HH24:MI'),
3, 2, 4, 16, 23);

/*Jornada 24*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('01-11-2026 10:01', 'DD-MM-YYYY HH24:MI'),
2, 1, 4, 3, 24);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('01-11-2026 11:37', 'DD-MM-YYYY HH24:MI'),
3, 2, 6, 16, 24);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('01-11-2026 12:55', 'DD-MM-YYYY HH24:MI'),
1, 3, 9, 7, 24);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('01-11-2026 12:09', 'DD-MM-YYYY HH24:MI'),
3, 1, 7, 9, 24);

/*Jornada 25*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('08-11-2026 14:38', 'DD-MM-YYYY HH24:MI'),
1, 3, 16, 3, 25);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('08-11-2026 18:46', 'DD-MM-YYYY HH24:MI'),
2, 1, 13, 7, 25);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('08-11-2026 16:17', 'DD-MM-YYYY HH24:MI'),
2, 3, 14, 2, 25);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('08-11-2026 18:40', 'DD-MM-YYYY HH24:MI'),
3, 1, 4, 16, 25);

/*Jornada 26*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('15-11-2026 14:16', 'DD-MM-YYYY HH24:MI'),
1, 3, 16, 3, 26);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('15-11-2026 15:13', 'DD-MM-YYYY HH24:MI'),
3, 1, 7, 14, 26);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('15-11-2026 17:09', 'DD-MM-YYYY HH24:MI'),
1, 3, 12, 2, 26);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('15-11-2026 10:38', 'DD-MM-YYYY HH24:MI'),
3, 1, 15, 16, 26);

/*Jornada 27*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('22-11-2026 16:19', 'DD-MM-YYYY HH24:MI'),
3, 2, 10, 1, 27);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('22-11-2026 17:36', 'DD-MM-YYYY HH24:MI'),
2, 1, 9, 12, 27);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('22-11-2026 11:01', 'DD-MM-YYYY HH24:MI'),
3, 2, 9, 6, 27);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('22-11-2026 10:07', 'DD-MM-YYYY HH24:MI'),
1, 2, 8, 7, 27);

/*Jornada 28*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('29-11-2026 18:59', 'DD-MM-YYYY HH24:MI'),
3, 2, 14, 10, 28);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('29-11-2026 14:25', 'DD-MM-YYYY HH24:MI'),
1, 3, 7, 8, 28);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('29-11-2026 10:14', 'DD-MM-YYYY HH24:MI'),
3, 2, 1, 7, 28);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('29-11-2026 13:11', 'DD-MM-YYYY HH24:MI'),
3, 1, 4, 3, 28);

/*Jornada 29*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-12-2026 14:50', 'DD-MM-YYYY HH24:MI'),
2, 3, 8, 7, 29);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-12-2026 17:02', 'DD-MM-YYYY HH24:MI'),
1, 2, 2, 10, 29);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-12-2026 15:52', 'DD-MM-YYYY HH24:MI'),
2, 3, 9, 6, 29);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('06-12-2026 16:39', 'DD-MM-YYYY HH24:MI'),
1, 2, 14, 1, 29);

/*Jornada 30*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-12-2026 11:27', 'DD-MM-YYYY HH24:MI'),
2, 3, 6, 16, 30);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-12-2026 10:33', 'DD-MM-YYYY HH24:MI'),
3, 1, 7, 5, 30);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-12-2026 16:56', 'DD-MM-YYYY HH24:MI'),
2, 3, 12, 2, 30);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('13-12-2026 14:01', 'DD-MM-YYYY HH24:MI'),
2, 3, 10, 7, 30);


/* Competición 4 */

INSERT INTO COMPETICIONES (ID_COMPETICION, NOMBRE_COM, FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'VCT GAME CHANGERS', 
        TO_DATE('04-04-2028', 'DD-MM-YYYY'), 
        TO_DATE('04-04-2029', 'DD-MM-YYYY'), 'A', 12, NULL);

/* Equipos competición 4 */
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (3, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (8, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (7, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (9, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (1, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (10, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (4, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (2, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (5, 4, 0, 0);
INSERT INTO EQUIPOS_COMPETICIONES (ID_EQUIPO, ID_COMPETICION, VICTORIAS, PUNTOS)
VALUES (6, 4, 0, 0);

/* Jornadas competición 4 */
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('24-05-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 2, TO_DATE('31-05-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 3, TO_DATE('07-06-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 4, TO_DATE('14-06-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 5, TO_DATE('21-06-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 6, TO_DATE('28-06-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 7, TO_DATE('05-07-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 8, TO_DATE('12-07-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 9, TO_DATE('19-07-2028', 'DD-MM-YYYY'), 4);
INSERT INTO JORNADAS (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 10, TO_DATE('26-07-2028', 'DD-MM-YYYY'), 4);

/* Enfrentamientos competición 4 */
/*Jornada 31*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-12-2028 14:05', 'DD-MM-YYYY HH24:MI'),
1, 2, 4, 10, 31);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-12-2028 12:47', 'DD-MM-YYYY HH24:MI'),
2, 3, 15, 3, 31);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-12-2028 10:01', 'DD-MM-YYYY HH24:MI'),
3, 1, 14, 13, 31);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('20-12-2028 13:24', 'DD-MM-YYYY HH24:MI'),
1, 2, 5, 7, 31);

/*Jornada 32*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-12-2028 16:13', 'DD-MM-YYYY HH24:MI'),
1, 2, 2, 4, 32);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-12-2028 13:55', 'DD-MM-YYYY HH24:MI'),
3, 1, 16, 13, 32);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-12-2028 17:12', 'DD-MM-YYYY HH24:MI'),
2, 1, 11, 3, 32);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('27-12-2028 11:24', 'DD-MM-YYYY HH24:MI'),
2, 1, 14, 10, 32);

/*Jornada 33*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('03-01-2028 11:14', 'DD-MM-YYYY HH24:MI'),
1, 3, 16, 9, 33);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('03-01-2028 15:37', 'DD-MM-YYYY HH24:MI'),
1, 3, 11, 9, 33);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('03-01-2028 14:22', 'DD-MM-YYYY HH24:MI'),
1, 2, 1, 5, 33);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('03-01-2028 15:15', 'DD-MM-YYYY HH24:MI'),
2, 3, 12, 2, 33);

/*Jornada 34*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('10-01-2028 18:37', 'DD-MM-YYYY HH24:MI'),
1, 3, 1, 13, 34);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('10-01-2028 13:10', 'DD-MM-YYYY HH24:MI'),
2, 1, 2, 3, 34);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('10-01-2028 12:02', 'DD-MM-YYYY HH24:MI'),
1, 3, 5, 7, 34);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('10-01-2028 14:14', 'DD-MM-YYYY HH24:MI'),
1, 2, 9, 3, 34);

/*Jornada 35*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('17-01-2028 15:50', 'DD-MM-YYYY HH24:MI'),
3, 2, 15, 2, 35);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('17-01-2028 14:41', 'DD-MM-YYYY HH24:MI'),
1, 3, 10, 3, 35);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('17-01-2028 16:32', 'DD-MM-YYYY HH24:MI'),
1, 3, 11, 5, 35);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('17-01-2028 14:46', 'DD-MM-YYYY HH24:MI'),
2, 1, 14, 15, 35);

/*Jornada 36*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-01-2028 14:31', 'DD-MM-YYYY HH24:MI'),
2, 3, 13, 4, 36);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-01-2028 11:33', 'DD-MM-YYYY HH24:MI'),
2, 1, 5, 13, 36);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-01-2028 13:04', 'DD-MM-YYYY HH24:MI'),
3, 2, 2, 10, 36);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('24-01-2028 17:08', 'DD-MM-YYYY HH24:MI'),
2, 3, 10, 11, 36);

/*Jornada 37*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-01-2028 11:26', 'DD-MM-YYYY HH24:MI'),
1, 3, 7, 11, 37);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-01-2028 10:54', 'DD-MM-YYYY HH24:MI'),
2, 1, 13, 2, 37);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-01-2028 16:16', 'DD-MM-YYYY HH24:MI'),
3, 2, 2, 16, 37);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('31-01-2028 18:28', 'DD-MM-YYYY HH24:MI'),
1, 3, 9, 1, 37);

/*Jornada 38*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-02-2028 12:32', 'DD-MM-YYYY HH24:MI'),
2, 1, 1, 7, 38);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-02-2028 12:24', 'DD-MM-YYYY HH24:MI'),
2, 3, 12, 13, 38);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-02-2028 14:17', 'DD-MM-YYYY HH24:MI'),
2, 3, 3, 4, 38);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('07-02-2028 11:00', 'DD-MM-YYYY HH24:MI'),
3, 2, 12, 8, 38);

/*Jornada 39*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-02-2028 16:32', 'DD-MM-YYYY HH24:MI'),
2, 1, 7, 13, 39);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-02-2028 10:38', 'DD-MM-YYYY HH24:MI'),
2, 1, 14, 15, 39);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-02-2028 11:50', 'DD-MM-YYYY HH24:MI'),
3, 1, 9, 16, 39);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('14-02-2028 16:25', 'DD-MM-YYYY HH24:MI'),
3, 2, 3, 2, 39);

/*Jornada 40*/
INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-02-2028 17:28', 'DD-MM-YYYY HH24:MI'),
2, 3, 2, 11, 40);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-02-2028 12:09', 'DD-MM-YYYY HH24:MI'),
1, 2, 6, 10, 40);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-02-2028 12:59', 'DD-MM-YYYY HH24:MI'),
3, 2, 7, 11, 40);

INSERT INTO ENFRENTAMIENTOS (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('21-02-2028 12:55', 'DD-MM-YYYY HH24:MI'),
1, 3, 5, 11, 40);

INSERT INTO USUARIOS (NOM_USUARIO, CONTRASENA, TIPO)
VALUES ('Za','Za1','A');

INSERT INTO USUARIOS (NOM_USUARIO, CONTRASENA, TIPO)
VALUES ('Lorena','Lorena1','N');

INSERT INTO USUARIOS (NOM_USUARIO, CONTRASENA, TIPO)
VALUES ('Ibai','Ibai1','N');

INSERT INTO USUARIOS (NOM_USUARIO, CONTRASENA, TIPO)
VALUES ('Julen','Julen1','N');

INSERT INTO USUARIOS (NOM_USUARIO, CONTRASENA, TIPO)
VALUES ('David','David1','N');


COMMIT;
