CREATE OR REPLACE PACKAGE PAQUETE_DATOS_CABECERA
IS
	PROCEDURE OBTENER_INFO_COMPETICION(c_obtenerInfoCompeticion OUT SYS_REFCURSOR);
	PROCEDURE OBTENER_INFORMACION(c_obtenerInfo out SYS_REFCURSOR);
END;


CREATE OR REPLACE PACKAGE BODY PAQUETE_DATOS_CUERPO
AS
	
	PROCEDURE OBTENER_INFO_COMPETICION(c_obtenerInfoCompeticion OUT SYS_REFCURSOR)
	AS
	BEGIN
		DECLARE
		BEGIN
			...;
		END;
	END OBTENER_INFO_COMPETICION;


	--

END;
