/*PRUEBA PARA EL PRIMER TRIGGER*/
/*EJEMPLO DE UN MAL INSERT (SI TIENE MENOS DE 2)*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Fnatic', TO_DATE('23-06-2004', 'DD-MM-YYYY'));

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kaelan', 'JDinooPvP', 'Reino Unido',
        'Jugador', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 4335.61, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('matalyn', 'Puppygamer02', 'Corea del Sur',
        'Jugador', TO_DATE('08-09-1993', 'DD-MM-YYYY'), 4928.08, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('anyi', 'LunaEclipse135', 'Estados Unidos',
        'Jugador', TO_DATE('09-01-2001', 'DD-MM-YYYY'), 2903.51, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('demarrion', 'Laziness_', 'Australia',
        'Jugador', TO_DATE('29-12-1990', 'DD-MM-YYYY'), 5975.62, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('abril', 'PayHra', 'India',
        'Jugador', TO_DATE('07-08-1996', 'DD-MM-YYYY'), 4677.36, 1);
        
DELETE FROM JUGADOR
WHERE NICKNAME IN ('Puppygamer02', 'LunaEclipse135'
, 'Laziness_', 'PayHra', 'JDinooPvP');

/*EJEMPLO DE UN MAL INSERT (SI TIENE MAS DE 6)*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Fnatic', TO_DATE('23-06-2004', 'DD-MM-YYYY'));

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('suzzanne', 'Koeleknul06', 'Reino Unido', 'Jugador',
TO_DATE('23-10-1995', 'DD-MM-YYYY'), 6636.99, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tyquarius', 'MoisesFGX', 'Francia', 'Jugador',
TO_DATE('26-04-2001', 'DD-MM-YYYY'), 6332.94, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('taina', 'Ebbitt', 'Alemania', 'Jugador',
TO_DATE('16-01-1990', 'DD-MM-YYYY'), 5082.05, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tatiana', 'Ebbitxt', 'Alemania', 'Jugador',
TO_DATE('18-01-1990', 'DD-MM-YYYY'), 5081.15, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gelisa', 'TheThorst', 'Estados Unidos', 'Lider',
TO_DATE('20-08-1991', 'DD-MM-YYYY'), 4986.7, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('talise', 'trooper2017', 'Italia', 'Lider',
TO_DATE('02-01-2005', 'DD-MM-YYYY'), 4568.19, 1);


/*PRUEBA PARA PROBAR EL SEGUNDO TRIGGER */
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'));

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 1);

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Fnatic', TO_DATE('23-06-2004', 'DD-MM-YYYY'));

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 2);

INSERT INTO JORNADA (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('02-05-2024', 'DD-MM-YYYY'), 1);

INSERT INTO ENFRENTAMIENTO (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-05-2024 15:34', 'DD-MM-YYYY HH24:MI'),
1, 2, 1, 2, 1);


/*PRUEBA PARA EL TERCER TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Mad Lions', TO_DATE('31-08-2017', 'DD-MM-YYYY'));
INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'C', 3, NULL);
UPDATE EQUIPO E
SET E.NOM_EQUIPO = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = E.ID_EQUIPO
    AND C.ETAPA = 'A'
);

/*EJEMPLO DE UN BUEN INSER*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Mad Lions', TO_DATE('31-08-2017', 'DD-MM-YYYY'));
INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'A', 3, NULL);
UPDATE EQUIPO E
SET E.NOM_EQUIPO = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = E.ID_EQUIPO
    AND C.ETAPA = 'A'
);
/*PRUEBA PARA EL CUARTO TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Mad Lions', TO_DATE('31-08-2017', 'DD-MM-YYYY'));
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('mesa', '_IRyzuStyles_', 'Japón', 'Jugador',
TO_DATE('06-09-2002', 'DD-MM-YYYY'), 5679.15, 5);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('phillips', 'CoolGirl2414', 'Australia', 'Lider',
TO_DATE('23-02-2006', 'DD-MM-YYYY'), 5759.18, 5);
INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'C', 3, NULL);
UPDATE JUGADOR J
SET J.NOMBRE = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = J.ID_EQUIPO
    AND C.ETAPA = 'A'
);
/*EJEMPLO DE UN BUEN INSER*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'Mad Lions', TO_DATE('31-08-2017', 'DD-MM-YYYY'));
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dalina', 'LittleBj', 'Reino Unido', 'Lider',
TO_DATE('09-07-2002', 'DD-MM-YYYY'), 5212.76, 6);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('dawsyn', 'And_0', 'Australia', 'Jugador',
TO_DATE('10-04-2000', 'DD-MM-YYYY'), 5372.46, 6);
INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'A', 3, NULL);
UPDATE JUGADOR J
SET J.NOMBRE = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = J.ID_EQUIPO
    AND C.ETAPA = 'A'
);

/*PRUEBA PARA EL QUINTO TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION)
VALUES (DEFAULT, 'KOI', TO_DATE('15-12-2021', 'DD-MM-YYYY'));

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gwendalynn', 'Topblocker04', 'Canadá', 'Jugador',
TO_DATE('22-08-2004', 'DD-MM-YYYY'), 821.24, 3);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kemontae', 'stampylongbro', 'Australia', 'Jugador',
TO_DATE('11-02-1991', 'DD-MM-YYYY'), 025.88, 3);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('marlow', 'Captain_Mehh', 'India', 'Jugador',
TO_DATE('04-12-1998', 'DD-MM-YYYY'), 452.92, 3);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('neve', 'UnDeadSlender', 'España', 'Lider',
TO_DATE('07-10-2005', 'DD-MM-YYYY'), 366.13, 3);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tayon', 'SpuddaKing', 'Francia', 'Lider',
TO_DATE('26-04-1994', 'DD-MM-YYYY'), 269.21, 3);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('skye', 'xEnderFighterx', 'Reino Unido', 'Jugador',
TO_DATE('17-09-1997', 'DD-MM-YYYY'), 824.79, 3);


/*PRUEBA PARA EL SEXTO TRIGGER */
SELECT *
FROM EQUIPO_COMPETICION
Where ID_COMPETICION = 1
ORDER BY VICTORIAS DESC, PUNTOS DESC;
