/*PRUEBA PARA EL PRIMER TRIGGER*/
/*EJEMPLO DE UN MAL INSERT (SI TIENE MENOS DE 2)*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'),
       'https://i.imgur.com/nuYSo51.png', 'Azul');

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kaelan', 'JDinooPvP', 'Reino Unido',
        'Jugador', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 4335.61, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('matalyn', 'Puppygamer02', 'Corea del Sur',
        'Jugador', TO_DATE('08-09-1993', 'DD-MM-YYYY'), 4928.08, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('anyi', 'LunaEclipse135', 'Estados Unidos',
        'Jugador', TO_DATE('09-01-2001', 'DD-MM-YYYY'), 2903.51, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('demarrion', 'Laziness_', 'Australia',
        'Jugador', TO_DATE('29-12-1990', 'DD-MM-YYYY'), 5975.62, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('abril', 'PayHra', 'India',
        'Jugador', TO_DATE('07-08-1996', 'DD-MM-YYYY'), 4677.36, 1);
        
DELETE FROM JUGADOR
WHERE NICKNAME IN ('Puppygamer02', 'LunaEclipse135'
, 'Laziness_', 'PayHra', 'JDinooPvP');

/*EJEMPLO DE UN MAL INSERT (SI TIENE MAS DE 6)*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://i.imgur.com/dPoFDgH.png', 'Naranja');

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tristan', 'Froont', 'Rusia',
        'Lider', TO_DATE('10-10-1994', 'DD-MM-YYYY'), 6177.99, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gabrille', '_BlackWinter_', 'Argentina',
        'Jugador', TO_DATE('13-07-1994', 'DD-MM-YYYY'), 2345.42, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('jevonte', 'Creepz630', 'Argentina',
        'Jugador', TO_DATE('09-07-1998', 'DD-MM-YYYY'), 4184.01, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('shaheim', 'dman1324', 'Corea del Sur',
        'Jugador', TO_DATE('22-03-1996', 'DD-MM-YYYY'), 2062.05, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('deeann', 'Jadco77', 'India',
        'Jugador', TO_DATE('12-02-1991', 'DD-MM-YYYY'), 5949.87, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('quran', 'Glamorousreese', 'Rusia',
        'Jugador', TO_DATE('17-07-2005', 'DD-MM-YYYY'), 3075.35, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('quranz', 'Glamorousreese', 'Rusia',
        'Jugador', TO_DATE('17-07-2005', 'DD-MM-YYYY'), 7075.35, 2);


/*PRUEBA PARA PROBAR EL SEGUNDO TRIGGER */
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://i.imgur.com/dPoFDgH.png', 'Naranja');

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tristan', 'Froont', 'Rusia',
        'Lider', TO_DATE('10-10-1994', 'DD-MM-YYYY'), 6177.99, 2);

INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://i.imgur.com/dPoFDgH.png', 'Naranja');

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tristan', 'Froont', 'Rusia',
        'Lider', TO_DATE('10-10-1994', 'DD-MM-YYYY'), 6177.99, 2);

INSERT INTO JORNADA (ID_JORNADA, NUM_JORNADA, FECHA_JORNADA, ID_COMPETICION)
VALUES (DEFAULT, 1, TO_DATE('02-05-2024', 'DD-MM-YYYY'), 1);

INSERT INTO ENFRENTAMIENTO (ID_ENFRENTAMIENTO, HORA_ENFRENTAMIENTO,
RESULTADO1, RESULTADO2, ID_EQUIPO1, ID_EQUIPO2, ID_JORNADA)
VALUES (DEFAULT, TO_TIMESTAMP('02-05-2024 15:34', 'DD-MM-YYYY HH24:MI'),
1, 2, 1, 2, 1);


/*PRUEBA PARA EL TERCER TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'),
       'https://i.imgur.com/nuYSo51.png', 'Azul');

INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'C', 3, NULL);       
UPDATE EQUIPO E
SET E.NOM_EQUIPO = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = E.ID_EQUIPO
    AND C.ETAPA = 'A'
);

/*EJEMPLO DE UN BUEN INSER*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://i.imgur.com/dPoFDgH.png', 'Naranja');

INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'A', 3, NULL);       
UPDATE EQUIPO E
SET E.NOM_EQUIPO = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = E.ID_EQUIPO
    AND C.ETAPA = 'A'
);
/*PRUEBA PARA EL CUARTO TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'),
       'https://i.imgur.com/nuYSo51.png', 'Azul');
       
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('lidiya', 'Squeezy_Cow', 'Francia', 'Jugador',
TO_DATE('03-08-1997', 'DD-MM-YYYY'), 4076.86, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kaelan', 'JDinooPvP', 'Reino Unido',
        'Jugador', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 4335.61, 1);

INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'C', 3, NULL);
UPDATE JUGADOR J
SET J.NOMBRE = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = J.ID_EQUIPO
    AND C.ETAPA = 'A'
);
/*EJEMPLO DE UN BUEN INSER*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Fnatic', TO_DATE('10-07-2004', 'DD-MM-YYYY'),
       'https://i.imgur.com/dPoFDgH.png', 'Naranja');
       
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('tristan', 'Froont', 'Rusia',
        'Lider', TO_DATE('10-10-1994', 'DD-MM-YYYY'), 6177.99, 2);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('gabrille', '_BlackWinter_', 'Argentina',
        'Jugador', TO_DATE('13-07-1994', 'DD-MM-YYYY'), 2345.42, 2);

INSERT INTO COMPETICION (ID_COMPETICION, NOMBRE_COM,
 	FECHA_INICIO, FECHA_FIN, ETAPA, ID_JUEGO, ID_EQUIPO_GANADOR)
VALUES (DEFAULT, 'CS2 MAJOR COPENHAGEN 2024', 
		TO_DATE('17-03-2024', 'DD-MM-YYYY'), 
		TO_DATE('31-03-2024', 'DD-MM-YYYY'), 'A', 3, NULL);
UPDATE JUGADOR J
SET J.NOMBRE = 'Nuevo Nombre'
WHERE EXISTS (
    SELECT 1
    FROM COMPETICION C
    JOIN EQUIPO_COMPETICION EC ON C.ID_COMPETICION = EC.ID_COMPETICION
    WHERE EC.ID_EQUIPO = J.ID_EQUIPO
    AND C.ETAPA = 'A'
);

/*PRUEBA PARA EL QUINTO TRIGGER*/
/*EJEMPLO DE UN MAL INSERT*/
INSERT INTO EQUIPO (ID_EQUIPO, NOM_EQUIPO, FECHA_FUNDACION, LOGO, COLOR)
VALUES (DEFAULT, 'Team Liquid', TO_DATE('15-09-2000', 'DD-MM-YYYY'),
       'https://i.imgur.com/nuYSo51.png', 'Azul');

INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('haileyann', 'Raptorella', 'Japón',
        'Lider', TO_DATE('20-08-1997', 'DD-MM-YYYY'), 001.69, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('kaelan', 'JDinooPvP', 'Reino Unido',
        'Jugador', TO_DATE('23-04-2006', 'DD-MM-YYYY'), 335.61, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('matalyn', 'Puppygamer02', 'Corea del Sur',
        'Jugador', TO_DATE('08-09-1993', 'DD-MM-YYYY'), 928.08, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('anyi', 'LunaEclipse135', 'Estados Unidos',
        'Jugador', TO_DATE('09-01-2001', 'DD-MM-YYYY'), 903.51, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('demarrion', 'Laziness_', 'Australia',
        'Jugador', TO_DATE('29-12-1990', 'DD-MM-YYYY'), 975.62, 1);
INSERT INTO JUGADOR
(NOMBRE, NICKNAME, NACIONALIDAD, ROL, FECHA_NAC, SUELDO, ID_EQUIPO)
VALUES ('abril', 'PayHra', 'India',
        'Jugador', TO_DATE('07-08-1996', 'DD-MM-YYYY'), 677.36, 1);


/*PRUEBA PARA EL SEXTO TRIGGER */
SELECT *
FROM EQUIPO_COMPETICION
Where ID_COMPETICION = 1
ORDER BY VICTORIAS DESC, PUNTOS DESC;
